---
channel: stable
addons:
  step-ca-client:
    repository: miguelangel-nubla/hassio-step-ca-client
    target: step-ca-client
    image: ghcr.io/miguelangel-nubla/hassio-step-ca-client/{arch}
    
