arch:
- aarch64
- amd64
- armhf
- armv7
- i386
auth_api: true
description: SSL/TLS certificates from your own PKI
hassio_api: true
hassio_role: manager
image: ghcr.io/miguelangel-nubla/step-ca-client/{arch}
init: false
map:
- ssl:rw
name: step-ca-client
options:
  ca_url: https://tinyca.internal
  cafile: ca.pem
  certfile: fullchain.pem
  key_type: RSA
  keyfile: privkey.pem
  log_level: info
  restart_addons:
  - core_mosquitto
  restart_ha: true
  root_ca_fingerprint: ''
  subjects:
  - homeassistant.local
  token: ''
schema:
  ca_url: url
  cafile: str
  certfile: str
  key_type: list(EC|OKP|RSA)
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  restart_addons:
  - str
  restart_ha: bool
  root_ca_fingerprint: str
  subjects:
  - str
  token: password
slug: step-ca-client
url: https://github.com/miguelangel-nubla/step-ca-client
version: 1.0.0
